### ISSUE TITLE
Cannot find module 'escape-html'

### ISSUE THREAD

**Issue by bugsyb** [danvk/localturk#24]
Hi Dan,

Thanks for all update.
Updating my local version with sudo npm install -g localturk worked ok.

After upgrade below error has been :
```
module.js:544
    throw err;
    ^

Error: Cannot find module 'escape-html'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/localturk/node_modules/errorhandler/index.js:18:18)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)

```

I've fixed it by running:
`
sudo apt-get install node-escape-html
`

Having said that, I've noticed that npm installed file points to ".js" file and not the new ".ts".

Regards.

**Comment by danvk** [comment]
Thanks for the heads up. I've added the undeclared dep in the linked commit.

The .js files are executed is intentional. The .ts files are only for development.
